apiVersion: v1
kind: Service
metadata:
  name: mern-backend
  labels:
    app: mern
    tier: backend
spec:
  ports:
  - port: 5000
    targetPort: 5000
    name: backend-port
  selector:
    app: mern
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-backend
spec:
  selector:
    matchLabels:
      app: mern
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: mern
        tier: backend
    spec:
      containers:
      - name: mern-backend
        image: irwankilay/backend2:1
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mern-backend
              key: user
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mern-backend
              key: password
        - name: DATABASE_DATABASE
          value: peopleproduction
        - name: DATABASE_HOST
          value: database-1.c9rm2bsyvw8e.ap-southeast-1.rds.amazonaws.com
        - name: DATABASE_PORT
          value: "3306"
        - name: BASE_URL
          value: "https://"staging.irwankilay.com"
