apiVersion: v1
kind: Service
metadata:
  name: mern-backend
  labels:
    app: mern
    tier: backend
spec:
  ports:
  - port: 5000
    targetPort: 5000
    name: backend-port
  selector:
    app: mern
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-backend
spec:
  selector:
    matchLabels:
      app: mern
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: mern
        tier: backend
    spec:
      containers:
      - name: mern-backend
        image: 898130718046.dkr.ecr.ap-south-1.amazonaws.com/big-project-backend:IMAGE_TAG
        resources:
          limits:
            memory: 500Mi
            cpu: 100m
          requests:
            memory: 80Mi
            cpu: 50m
        ports:
        - containerPort: 5000
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mern-backend
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mern-backend
              key: password
        - name: DB_DATABASE
          value: peopleproduction
        - name: DB_HOST
          value: database-1-ikhsan.cjy93ctary5j.ap-south-1.rds.amazonaws.com